[book]
title = "The End is Nigh: Modding Manual"
authors = [ "Joshua Robertson", "Thief3", "Stuart Mouse" ] # Feel free to add your name if you help out!
description = "A modding guide for the game The End is Nigh."
src = "source"
language = "en"

[output.html]
theme = "source/theme"
default-theme = "ayu"
preferred-dark-scheem = "ayu"
git-repository-url = "https://github.com/JROB774/tein-manual"

[output.html.fold]
enable = true
