[book]
title = "The End is Nigh: Modding Manual"
description = "A modding guide for the game The End is Nigh."
authors = [ "Joshua Robertson", "Malik Kissarli" ]
src = "source"
language = "en"

[output.html]
theme = "source/theme"
default-theme = "navy"
preferred-dark-scheem = "navy"
git-repository-url = "https://github.com/JROB774/tein-manual"

[output.html.fold]
enable = true
